namespace CryptoCurrency.Core.Symbol
{
    public enum SymbolCodeEnum
    {
        BTCAUD = 2,
        BTCUSD = 3,
        BTCUSDLONGS = 4,
        BTCUSDSHORTS = 5,
        BTCUSDT = 6,
        ETCAUD = 7,
        ETHAUD = 8,
        ETHBTC = 9,
        ETHBTCLONGS = 10,
        ETHBTCSHORTS = 11,
        ETHUSD = 12,
        ETHUSDLONGS = 13,
        ETHUSDSHORTS = 14,
        ETHUSDT = 15,
        LTCAUD = 16,
        LTCBTC = 17,
        LTCBTCLONGS = 18,
        LTCBTCSHORTS = 19,
        LTCUSD = 20,
        LTCUSDLONGS = 21,
        LTCUSDSHORTS = 22,
        LTCUSDT = 23,
        XLMBTC = 24,
        XLMETH = 25,
        BNBBTC = 26,
        NEOBTC = 27,
        QTUMETH = 28,
        EOSETH = 29,
        SNTETH = 30,
        BNTETH = 31,
        GASBTC = 32,
        BNBETH = 33,
        OAXETH = 34,
        DNTETH = 35,
        MCOETH = 36,
        MCOBTC = 37,
        WTCBT